config/routes.rb
Rails.application.routes.draw do
  resources :greetings
  root 'greetings#index'
  namespace :api do
    namespace :v1 do
      get 'greetings/random', to: 'greetings#random'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/greeting.rb
class Greeting < ApplicationRecord
end

app/controllers/api/v1/greetings_controller.rb
class Api::V1::GreetingsController < ApplicationController
  def random
    greeting = Greeting.order('RANDOM()').first
    render json: greeting
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/greetings/_form.html.erb
<%= form_with(model: greeting) do |form| %>
  <% if greeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(greeting.errors.count, "error") %> prohibited this greeting from being saved:</h2>

      <ul>
        <% greeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :greeting, style: "display: block" %>
    <%= form.text_field :greeting %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/greetings/_greeting.html.erb
<div id="<%= dom_id greeting %>">
  <p>
    <strong>Greeting:</strong>
    <%= greeting.greeting %>
  </p>

</div>

app/views/greetings/edit.html.erb
<h1>Editing greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Show this greeting", @greeting %> |
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/index.html.erb
<div id="root"></div>

app/views/greetings/new.html.erb
<h1>New greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @greeting %>

<div>
  <%= link_to "Edit this greeting", edit_greeting_path(@greeting) %> |
  <%= link_to "Back to greetings", greetings_path %>

  <%= button_to "Destroy this greeting", @greeting, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webpack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>